### ISSUE TITLE
Test failed in copr

### ISSUE THREAD

**Issue by remilauzier** [RazrFalcon/svgtypes#10]
https://download.copr.fedorainfracloud.org/results/remilauzier/plotters/fedora-rawhide-x86_64/02251828-rust-svgtypes/builder-live.log.gz
Doctest failed in copr.

failures:

---- src/stream.rs - stream::Stream::advance (line 203) stdout ----
Test executable succeeded, but it's marked `should_panic`.

failures:
    src/stream.rs - stream::Stream::advance (line 203)

test result: FAILED. 16 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.56s

**Comment by RazrFalcon** [comment]
Yes, I know that Fedora likes to run tests in release mode for some reason, which is incompatible with Rust. Will see what I can do.
